### ISSUE TITLE
提升方法推导过程提问

### ISSUE THREAD

**Issue by stshuen** [SmirkCao/Lihang#101]
## 相关章节
CH08---提升方法
## 相关主题
- [ ] 代码
- [ ] 文档
- [ ] 示例

## 问题描述
AdaBoost算法最终分类器的训练误差界是怎么推导出来的: 
$$
\frac{1}{N}\sum\limits_{i=1}\limits^N I(G(x_i)\neq y_i)\le\frac{1}{N}\sum\limits_i\exp(-y_i f(x_i))=\prod\limits_m Z_m
$$
看第一版有详细的说明, 但是还有个地方不太明白是怎么推导出来的
$$
\frac{1}{N}\sum_i exp \left ( -\sum_{m=1}^M a_m y_i G_m(x_i)\right ) \\
= \sum_i w_{1i}\prod_{m=1}^M exp \left ( -a_m y_i G_m(x_i) \right) 
$$
麻烦老师讲解

**Comment by SmirkCao** [comment]
你看第二版$P_{156}$，初始化的$w_{1i}=\frac{1}{N}$
然后指数上面的求和可以转化成指数乘法，就有了后面的连乘
