### ISSUE TITLE
您好作者，请问为什么我打开不显示公式

### ISSUE THREAD

**Issue by yangninghua** [SmirkCao/Lihang#73]
## 问题描述
我使用了你说的
Chrome插件TeX All the Things
本地Markdown编辑器Typora
但是打开还是显示不全，因为是ubuntu系统吗？
![image](https://user-images.githubusercontent.com/32252319/55528897-262abf00-56d1-11e9-8eab-201ef997a216.png)
****

**Comment by yangninghua** [comment]
您好，我这种情况是正确的还是我没弄好

**Comment by SmirkCao** [comment]
@yangninghua 
Ubuntu没问题
![Screenshot from 2019-04-07 21-42-51](https://user-images.githubusercontent.com/35244986/55684535-75494c00-597e-11e9-9816-52ff1d196b0e.png)

请check下相关配置，
![Screenshot from 2019-04-07 21-43-30](https://user-images.githubusercontent.com/35244986/55684532-69f62080-597e-11e9-8527-501a271f1e0f.png)


> 您好，我这种情况是正确的还是我没弄好

**Comment by xpf7622** [comment]
TeX All the Things安装了，为啥.md文件在chrome中打开，数学公式还是有问题。显示不了。

**Comment by SmirkCao** [comment]
> TeX All the Things安装了，为啥.md文件在chrome中打开，数学公式还是有问题。显示不了。

![Screenshot from 2019-04-12 11-45-37](https://user-images.githubusercontent.com/35244986/56011070-9ca26f00-5d18-11e9-9fdb-55d0d56e1b13.png)
![Screenshot from 2019-04-12 11-45-47](https://user-images.githubusercontent.com/35244986/56011073-9d3b0580-5d18-11e9-99c7-6fd5c2cb36c3.png)
这俩图一个开启了，一个没开启。

要针对站点点开，点开之后刷新下。
